apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: test
spec:
  containers:
  - name: myfirstflask
    image: gcr.io/tgigout/myfirst
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
